language: generic 
sudo: required
services: 
  - docker
script:
  - docker run -e CI=true xinboxia/react-test npm test

before_install:
  - docker build -t xinboxia/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xinboxia/react-test npm test

after_success:
  - docker build -t xinboxia/multi-client ./client
  - docker build -t xinboxia/multi-nginx ./nginx
  - docker build -t xinboxia/multi-server ./server
  - docker build -t xinboxia/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push xinboxia/multi-client
  - docker push xinboxia/multi-nginx
  - docker push xinboxia/multi-server
  - docker push xinboxia/multi-worker