language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t xinboxia/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true xinboxia/react-test npm test

after_success:
  - docker build -t xinboxia/multi-client -f ./client
  - docker build -t xinboxia/multi-nginx -f ./nginx
  - docker build -t xinboxia/multi-server -f ./server
  - docker build -t xinboxia/multi-worker -f ./worker